package hu.progmatic.carnivora;

public enum ConservationStatus {
    KIHALT,
    VADON_KIHALT,
    FENYEGETETT,
    SULYOSAN_VESZELYEZTETETT,
    VESZELYEZTETETT,
    SEBEZHETO,
    MERSEKELTEN_FENYEGETETT,
    NEM_FENYEGETETT,
    HAZIASITOTT
}
