spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carnivora
    username: progmatic
    password: progmatic
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    livereload:
      port: 35730
    restart:
      exclude: templates/**
  #mail:
  #  host: smtp.gmail.com
  #  port: 587
  #  username: carnivora.project@gmail.com
  #  password: azqiaivcrupiyrvs
  #  properties:
  #    mail:
  #      smtp:
  #        auth: true
  #        starttls:
  #          enable: true
  #  default-encoding: UTF-8
  #  protocol: smtp
  #  test-connection: false
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

output:
    ansi:
      enabled: ALWAYS
server:
  port: 8084
logging:
  level:
    web: DEBUG
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%15X{user}){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx}'
---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: tesztuser
    password: tesztpass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true