version: "3.7"

services:
  adatbazis_eles:
    container_name: kozos-projekt-eles-adatbazis
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carnivora
      MYSQL_USER: progmatic
      MYSQL_PASSWORD: progmatic
    ports:
      - "3309:3306"
    volumes:
      - vol_kozos_eles_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my-progmatic.cnf
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  email_dev:
    image: maildev/maildev
    container_name: email_dev
    ports:
      - "1025:1025"
    restart: always
  app_eles:
    container_name: kozos-project-eles
    build: ..
    environment:
      - PROFILES=eles
      - TZ=Europe/Budapest
    ports:
    - "80:80"
    - "8080:8080"
    depends_on:
      - adatbazis_eles
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "--insecure", "http://localhost:8080/" ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 120s
    restart: always
volumes:
  vol_kozos_eles_data:
    external:
      name: kozos_eles_data