package hu.progmatic.carnivoraProject;

public enum VeszelyeztetettKategoriak {
  KIHALT,
  VADON_KIHALT,
  FENYEGETETT,
  SULYOSAN_VESZELYEZTETETT,
  VESZELYEZTETETT,
  SEBEZHETO,
  MERSEKELTEN_FENYEGETETT,
  NEM_FENYEGETETT,
  HAZIASITOTT
}
